apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo-app 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: hiteshtp/todo-app
        ports:
        - containerPort: 80
        volumeMounts:
        - name: todo-pvc
          mountPath: /home/ubuntu/data
      volumes:
      - name: todo-pvc
        persistentVolumeClaim:
          claimName: todo-pvc


